### ISSUE TITLE
How to connect with database using node.js

### ISSUE THREAD

**Issue by jewelmir81** [nodeschool/dhaka#1]
I want to connect with sql server using node.js and want to DDL & DML operation using node.js
Is it possible? If possible, how?

**Comment by az7arul** [comment]
Yes definitely, you can use http://sequelizejs.com which works for mysql, postgresql, sqlite etc.

**Comment by riyadhalnur** [comment]
If you want to write pure SQL statements, then are native npm packages https://www.npmjs.com/package/mysql (for MySQL) and https://www.npmjs.com/package/pg (for PostGreSQL)
