### ISSUE TITLE
NodeSchool Dhaka Event ( Only for students of UITS)

### ISSUE THREAD

**Issue by prappo** [nodeschool/dhaka#14]
I talked to Al Imtiaz sir about event and he agreed with that but need  more discussion with him for details . 
mentors please .

**Comment by atiqueahmedziad** [comment]
Any Estimate date?

**Comment by prappo** [comment]
not yet , i will update the time and date after confirmation .

**Comment by zhdzmn** [comment]
Will be there. Go for it !!

**Comment by az7arul** [comment]
+1

**Comment by Shafiul-Hasan-tareq** [comment]
+1

**Comment by raihantaher** [comment]
I am not a student of UITS nor an organizer of NodeSchoolDhaka. But i want to be part of the NodeSchoolDhaka. Is there any way to be part of the organizers or work as a volunteer. Please let me know.

Thanks

**Comment by az7arul** [comment]
@raihantaher did you attend any of the nodeschool events ?

**Comment by raihantaher** [comment]
@az7arul yes, i was there at NodeSchool International Day event.

**Comment by az7arul** [comment]
You are in the nodeschool/dhaka team which means you are already a part of NodeSchool. Nodeschool is run by volunteers like you and me so feel free to take part.

**Comment by raihantaher** [comment]
Great. Thanks @az7arul

**Comment by az7arul** [comment]
@prappo any update on this ?

**Comment by prappo** [comment]
today i talked to Imtiaz sir and he said , he talked to his students about that and they are agree but from the next week semester final exam will be held so it should be after final exam

**Comment by riyadhalnur** [comment]
closing this for now
