### ISSUE TITLE
Showcase your node.js works @ nodeschool workshop

### ISSUE THREAD

**Issue by ishtiaque23** [nodeschool/dhaka#15]
We had a great time at the International day event. One of the most exciting part was the project showcase. Interested Participants get the chance to showcase their work in node js.

We are proposing to make it a regular thing in our workshops. I know the time is limited in the 2-3 hour event, but it will definitely help to boost up the interest of the members:

How it works:
1. Interested people should ask in this thread if they want to showcase something. 
2. They need to provide a `Title` for their project and a small `Description` explaining what it does.
3. Organizers will maintain the list of showcase topics. FIFO will be followed.
4. They will have to pick the presenters based on the time of workshop. For the regular format, only one showcase is possible. But in the day long events we definitely can accommodate more showcases. 
5. Organizers will facilitate the time slot for the selected presenters.

Let us know if you are interested.

**Comment by zhdzmn** [comment]
I am going to make a WIKI out of this as this is pretty much how we are doing it now.
