### ISSUE TITLE
NodeSchool Dhaka August Meetup?

### ISSUE THREAD

**Issue by raikusy** [nodeschool/dhaka#17]
Can anyone organize a open workshop or meetup? This is might be for beginners. Giving them guideline, resources etc. Letting them know the power of node.js. Why should they use node.js etc. This might empower the node.js Bangladesh community.

**Comment by Shafiul-Hasan-tareq** [comment]
Widespace Dhaka will organise one event very soon.

**Comment by raikusy** [comment]
Waiting for that :)

**Comment by hsleonis** [comment]
Nice

**Comment by theKhorshed** [comment]
Waiting for the Event :)

**Comment by sagormax** [comment]
I would like to join this event.
