### ISSUE TITLE
Next Nodeschool Event

### ISSUE THREAD

**Issue by riyadhalnur** [nodeschool/dhaka#18]
It's been quite a while since the last event. Anyone have ideas on where and when we can do the next one?

I'm personally leaning towards a non-university event. As for location, we have [Moar](https://www.facebook.com/moarbd?fref=ts).

**Comment by zhdzmn** [comment]
i am ok with it. A bit short on money now though :p

**Comment by riyadhalnur** [comment]
@zhdzmn haha i feel you, but we won't need much money if we were to do this at Moar and maybe skimp on the snacks.

**Comment by Shafiul-Hasan-tareq** [comment]
Widespace will arrange the place and snacks.  Lets have a short meeting on
the probable date.

**Comment by riyadhalnur** [comment]
:+1: @Shafiul-Hasan-tareq bhai sounds good

**Comment by az7arul** [comment]
+1

**Comment by zhdzmn** [comment]
I am all up for it :) lets talk sometime this week. Maybe Thursday. If that
works for everyone. We can meet at a coffee shop afternoon?

**Comment by riyadhalnur** [comment]
i'm not sure if i can make it for coffee in Banani. call me over skype if possible

**Comment by prappo** [comment]
count me in

**Comment by bleedingpoem** [comment]
I am in

**Comment by tanvirraj** [comment]
i'm in :+1:

**Comment by code-shoily** [comment]
I'm in :D

**Comment by code-shoily** [comment]
I can be there any day after 7:00 PM and any time during Saturday/Fridays... if the meeting falls during those time, I'd definitely come :)

**Comment by theKhorshed** [comment]
I am in.

**Comment by riyadhalnur** [comment]
when is the meeting then? and can we get an update on dates that Widespace will be able to provide space on @Shafiul-Hasan-tareq bhai?

**Comment by Shafiul-Hasan-tareq** [comment]
1st November is the most suitable time for us.

**Comment by zhdzmn** [comment]
Can we make it a Saturday. Alot of the ppl who are working wont b able to
make it if it is Sunday.

**Comment by Shafiul-Hasan-tareq** [comment]
We will have our internal Hackathon on next  29-30th Oct. So i have to
check with the guys whether they can arrange the Meet-up  just after the
Hackathon or not.

**Comment by zhdzmn** [comment]
We can postpone it to another week no rush.

**Comment by riyadhalnur** [comment]
do we have a tentative date? can you please confirm @Shafiul-Hasan-tareq bhai

**Comment by Shafiul-Hasan-tareq** [comment]
Hi All,

We are planning to arrange the event on 7th November from 10.00 am - 1.00
pm. So what do you think guys ?

Thanks,
Tareq

**Comment by riyadhalnur** [comment]
sounds good to me

**Comment by riyadhalnur** [comment]
can everyone else chime in please? is 7th final?

**Comment by az7arul** [comment]
I think 7 is most likely, @nafiboss is taking the lead on that

**Comment by riyadhalnur** [comment]
date is fixed for 14th. meet up event up here http://www.meetup.com/Dhaka-JS/events/226392130/
