### ISSUE TITLE
NodeSchool #1 @dhaka

### ISSUE THREAD

**Issue by az7arul** [nodeschool/dhaka#2]
Looking for people who are interested to play the mentor role in the event.

Tentative date is 1st/2nd week of February, 2015.

**Comment by thesabbir** [comment]
@az7arul I am in.

**Comment by theanam** [comment]
I'm in

**Comment by riyadhalnur** [comment]
in

**Comment by atiqueahmedziad** [comment]
I am in

**Comment by nc-rasel** [comment]
count me too :)

**Comment by hasinhayder** [comment]
can you pls share the details of the event?

**Comment by az7arul** [comment]
nodeschool workshops are typically done in a mentor/mentee format. A 1:5 ratio is ideal. What we would do is start people on different tutorials ( http://nodeschool.io/#workshoppers ) and help them get through it.

If someone has other ideas I am all ears. 

How many people we can invite to join the event is a bit dependent on how many mentors will be available. Once I get that, I will send an event invite to everyone who is interested to join.

**Comment by hasinhayder** [comment]
alright, sounds good. count me in

**Comment by az7arul** [comment]
Thanks for everyone's interest, I will reach out to everyone here next week to discuss next steps.

**Comment by emdadcse** [comment]
I am too interest :)

**Comment by prappo** [comment]
Me too

**Comment by mofrubel** [comment]
i'm interested

**Comment by az7arul** [comment]
let's meet this week to discuss the details. When's a good time for everyone ?

**Comment by az7arul** [comment]
let's meet this week to discuss the details. When's a good time for everyone ?
@thesabbir @theanam @riyadhalnur  @hasinhayder @nc-rasel  @mofrubel @prappo @emdadcse @atiqueahmedziad

**Comment by theanam** [comment]
any saturday / Sunday is best for me. @az7arul

**Comment by mofrubel** [comment]
Friday or Saturday would be a good choice.

**Comment by riyadhalnur** [comment]
yeah i guess weekends work best

**Comment by prappo** [comment]
Friday or Sunday is best for me @az7arul  bro .

**Comment by azmul** [comment]
Friday or Saturday are best for me.

**Comment by arnabsust** [comment]
I am in

**Comment by az7arul** [comment]
Let's meet up to discuss this. Is Feb 13 ( edited: friday ) good ?

**Comment by prappo** [comment]
Feb 13 is Friday . i think we can meet @az7arul  bro

**Comment by mofrubel** [comment]
13th Feb (Friday) not bad, eagerly waiting for that ...... @az7arul

**Comment by az7arul** [comment]
my bad, fixed the date. Lets fix a place to meet ( I prefer Gloria Jeans ) and discuss how we can arrange the nodeschool event.

**Comment by mofrubel** [comment]
Gloria Jeans (Gulshan-1)...? if so, i've no problem. @az7arul

**Comment by azmul** [comment]
13 th Feb is  better . To start discuss i personally think after jumma
 namaz is suitable for everyone.

**Comment by prappo** [comment]
i think making  a group in fb is better solution to communicate . cz almost everyone is active in fb and for quick notification it's good way so this is easy way to discuss and communicate each other .

**Comment by az7arul** [comment]
@prappo I personally don't use fb groups that much and other nodeschool chapters mostly use github. Having said that, if anyone takes the responsibility to share these updates in a fb group ( by creating one ) it is welcomed.

Nodeschool is a community event, feel free to do anything that you think is appropriate. Let me know what you think.

**Comment by az7arul** [comment]
So, 13 Feb it is ? 

We can discuss on this thread too. If anyone has any query don't hesitate

**Comment by theanam** [comment]
I have office tomorrow. can it be after 6 30, 7? gloria jeans which one?

**Comment by az7arul** [comment]
gulshan 1. I am happy to reschedule if thats what majority want

**Comment by prappo** [comment]
gulsan 1 perfect  . but after 3 pm is best  for me . and i think if you send us your contact number via email then it will be easier .  @az7arul

**Comment by az7arul** [comment]
its 0153467xxxx, so it seems evening is suitable for most.

**Comment by az7arul** [comment]
Lets meet at 6:00 PM at Gloria Jeans ( Gulshan 1). Who can make it ?

**Comment by theanam** [comment]
I'll be reaching by 6.30 (max)

**Comment by az7arul** [comment]
I am heading over there. See you guys there.

**Comment by azmul** [comment]
what is better between express.js and sails.js ?

**Comment by masnun** [comment]
sails is based on express. btw, you should create a separate thread for such discussions.

**Comment by prappo** [comment]
@az7arul  i dialed your number 2 times to contact but you didn't receive .

**Comment by az7arul** [comment]
@prappo  on friday ?

**Comment by prappo** [comment]
yes , @az7arul  . 
and i created a fb group for quick communication . 
https://www.facebook.com/groups/963486660336026/
feel free to join . thanks .

**Comment by az7arul** [comment]
I talked with NewsCred regarding the venue and they have agreed to provide us the space. 28th feb is already booked so we will be taking the March 7.

**Comment by az7arul** [comment]
http://www.meetup.com/Dhaka-JS/events/219379409/

**Comment by zhdzmn** [comment]
joining in

**Comment by raikusy** [comment]
I will definitely join :D Thanks for this awesome step!

**Comment by saddamcrr7** [comment]
waiting..

**Comment by jewelfarazi** [comment]
Good luck and waiting

**Comment by asad01304** [comment]
Count me in!

**Comment by az7arul** [comment]
@nodeschool/dhaka can you guys share the event through your channels ?

Site is also updated with the meetup link http://nodeschool.io/dhaka/

**Comment by nadimtuhin** [comment]
I will be in next month :+1:

**Comment by waliurjs** [comment]
I am in!

**Comment by az7arul** [comment]
@nodeschool/dhaka 7th of March is around the corner. @ishtiaque23 @riyadhalnur @zhdzmn @nodeschool/dhaka we need to set a few things up ( like ensuring offline installation of the nodeschool workshops) before it. When's a good time for you guys ?

**Comment by zhdzmn** [comment]
how about we discuss tomorrow.

**Comment by riyadhalnur** [comment]
anytime this week is good

**Comment by az7arul** [comment]
tomorrow ( March 2 ) is fine with me

**Comment by Pipash** [comment]
Count me in! very much interested..:)

**Comment by az7arul** [comment]
When is a good time tomorrow @zhdzmn ?

**Comment by zhdzmn** [comment]
@az7arul lets have lunch at 2

**Comment by az7arul** [comment]
cool

**Comment by az7arul** [comment]
http://www.meetup.com/Dhaka-JS/messages/boards/thread/48776226

**Comment by selimppc** [comment]
Count on me !!!!

**Comment by zhdzmn** [comment]
Thank you all who came to the event. see you again soon !! if there are any queries  please dont hesitate to post an issue here. Thank you !
