### ISSUE TITLE
Nodeschool Dhaka event at BRAC University!

### ISSUE THREAD

**Issue by excalliburbd** [nodeschool/dhaka#20]
Hello guys,
We're trying to host a Nodeschool event at BRAC University. Our labs have around 20 - 30 PCs and 1-4 projectors. We normally hold workshops after 5:00pm in our campus. We can set up Nodejs and the workshoppers beforehand. We could do the basic JavaScript workshop ourselves and then do the Nodejs one at the event or do both in one day. We have not yet suggested any dates so you are welcomed to suggest convenient times.

Mentors, your co-operation would be much appreciated :)

**Comment by riyadhalnur** [comment]
@excalliburbd Sounds great! We need more pro-activeness in the community. I would suggest though letting node schoolers on choosing the workshops they want to work on during the workshop. Workshops range from beginner to advanced so it doesn't make sense for everyone to do the same workshop.

I'm not sure how involved we can be with the event but I will try my best, personally, to help out as much as possible. Let me know once you have fixed a date.

**Comment by az7arul** [comment]
+1

**Comment by zhdzmn** [comment]
Will b there this time. Inshallah

Preferred day is saturday

**Comment by raihantaher** [comment]
I am interested.
