### ISSUE TITLE
International Day 2016

### ISSUE THREAD

**Issue by riyadhalnur** [nodeschool/dhaka#21]
Are we willing to do anything for International Day this year? @az7arul @ishtiaque23 @zhdzmn.

**Comment by az7arul** [comment]
We should but I am not sure if I will be in Bd that time.
On May 10, 2016 11:43 AM, "Riyadh Al Nur" notifications@github.com wrote:

Are we willing to do anything for International Day this year? @az7arul
https://github.com/az7arul @ishtiaque23 https://github.com/ishtiaque23
@zhdzmn https://github.com/zhdzmn.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
https://github.com/nodeschool/dhaka/issues/21

**Comment by ishtiaque23** [comment]
Yeah we have been away for a long time from this. International Day has its format. We can share our ideas here.

**Comment by riyadhalnur** [comment]
1. http://nodeschool.io/international-day/
2. https://github.com/nodeschool/international-day/blob/2016/ORGANISERS.md
3. https://github.com/nodeschool/international-day

**Comment by ishtiaque23** [comment]
https://github.com/nodeschool/international-day/blob/2016/PARTICIPATING.md shows nothing has changed from last time. So we know the drill.

But the fact is, the third link @riyadhalnur shared, it says "Enrollment Closes on May 1st at 18:00 GMT".
Though I am seeing only one chapter logo in the main site for 2016.

**Comment by ishtiaque23** [comment]
NVM, we can enroll I guess as the form is still active. We need to plan first though, about venue and program outline.

Let's meet up and discuss someday. @riyadhalnur, @az7arul, @zhdzmn

**Comment by riyadhalnur** [comment]
@az7arul When are you leaving and coming back?

**Comment by imnasif** [comment]
@riyadhalnur  Your Facebook post directed me here. Give me a buzz if help needed.

**Comment by zhdzmn** [comment]
I am creating a meetup event. I dont think we have time for the sponsors. Lets share the stuff like virus this 2 following days. I am free tomorrow. tell me when you guys want to plan the day.and for now I will try to get the newscred premise.

**Comment by zhdzmn** [comment]
https://gitter.im/nodeschool/dhaka

**Comment by zhdzmn** [comment]
http://www.meetup.com/Dhaka-JS/events/231171189/

**Comment by prappo** [comment]
count me in +

**Comment by zhdzmn** [comment]
I am canceling the meetup. It is a very short time. and we are unable to make this in time. Sorry guys
