### ISSUE TITLE
I think it is time

### ISSUE THREAD

**Issue by zhdzmn** [nodeschool/dhaka#22]
I think it is time to meetup again.
nodeschool in dhaka has been inactive for a long time.

in addition to that I am interested in starting a conversation about a **jsConf**. we will need good speakers and suggestions on the format.

**Comment by tanvirraj** [comment]
:thumbsup:

**Comment by newazsharif** [comment]
I agree

**Comment by jeebon** [comment]
Waiting for.

**Comment by prappo** [comment]
+1

**Comment by mones-cse** [comment]
(y)

**Comment by az7arul** [comment]
+1

**Comment by nurrony** [comment]
I am really excited meeting some cool NodeJS people in Dhaka. I also wanna be a member of NodeSchool Dhaka. Don't know the rules. Anybody out there who can help me 😉

**Comment by az7arul** [comment]
@zhdzmn let's do something on 2nd week of November.

**Comment by nurrony** [comment]
@zhdzmn @az7arul Did you come up with any good news? Eagerly waiting for it

**Comment by zhdzmn** [comment]
https://github.com/nodeschool/dhaka/issues/24
