### ISSUE TITLE
Nodeschool Dhaka 2018

### ISSUE THREAD

**Issue by sgtlaugh** [nodeschool/dhaka#25]
Tentative date: July 28 2018, 02:00 pm to 06:00 pm BDT.
Location: NewsCred

Lets discuss about the event here. Don't forget to leave a comment if you are interested and will be coming to join :)

**Comment by faisalhmohd** [comment]
Looks like a good date to get things started. Hoping others would hop in so that we can make this happen!

**Comment by zhdzmn** [comment]
Sounds amazing !!!

**Comment by zhdzmn** [comment]
What is the agenda where is it happening and who are the mentors? And if
there is a mentor registration happening?

**Comment by theKhorshed** [comment]
Wow! Interested to join!

**Comment by faisalhmohd** [comment]
@zhdzmn It is set to happen at NewsCred Dhaka office (Banani). Looking forward for responses so that we can 'actually' host it. 
So far, me and @sabit-zahin have elected ourselves as mentors, but if any of you are interested, feel free to drop a message here or ping me. 
Good news is, this time, we will have gifts for participants who demo their pet project built with NodeJS. Encouraging everyone to participate. 
More news will be coming in shortly, stay tuned!

**Comment by riyadhalnur** [comment]
Good stuff. Wish I could join

**Comment by prappo** [comment]
count me in

**Comment by sgtlaugh** [comment]
Checkout the meetup:
https://www.meetup.com/Dhaka-JS/events/252392286/

Also, mentors are welcome, so leave a comment expressing your interest if you want to be a mentor in this event.

**Comment by sh1hab** [comment]
Do i need to register somewhere or just hop in?

**Comment by zhdzmn** [comment]
@sh1hb http://meetu.ps/e/Fw0kP/tcQhC/d register here

**Comment by aqifcse** [comment]
The site is https://nodeschool.io/dhaka/ showing July 28 2018, 03:00 pm to 07:00 pm BDT. So, what is the exact time actually??

**Comment by faisalhmohd** [comment]
@aqifcse As shown by the site, the meetup link and your comment, the event timeline is from 3PM to 7PM BDT @ July 28th 2018. Hope that clears your query.

**Comment by aqifcse** [comment]
Any procedure to register or just go on the spot.... ?

**Comment by faisalhmohd** [comment]
@aqifcse it is an open event, but RSVP's are prioritized more. Register here - http://meetu.ps/e/Fw0kP/tcQhC/d

**Comment by aqifcse** [comment]
That was really helpful.Thank you.

**Comment by faahim** [comment]
Loved it!! Enjoyed it very very much. Thanks everyone involved for making this happen. 
I'd really love to attend a monthly event like this. Is that something you guys are considering? ☺️

**Comment by faisalhmohd** [comment]
@faahim at the moment, organising monthly would be difficult, but we would try our best to host once every 6 months. Stay tuned! Also glad that you enjoyed the event!

**Comment by menomanabdulla** [comment]
is there anything (like: slide,project show,topics that you covered or any
suggestions) for whose not able to join the excellent event.

Thank you.

**Comment by faisalhmohd** [comment]
@menomanabdulla well nodeschool is a workshop where everyone work on their projects or try out the `nodeschool.io` workshops, get feedback on their work, network, get to know more on NodeJS or any other language, etc. (kinda like a meetup/hangout), so unfortunately, there isn't any slide/topics covered. You can checkout the live video here https://www.facebook.com/newscreddhaka/videos/2089469954647251/ where there were a lot of great demos given by amazing people!
Hope that satisfies your needs!

**Comment by faahim** [comment]
@faisalhmohd That sounds great! I look forward to our next event. Also, I'd be willing to help to organize the events in any way within my capabilities. So, if you guys need a hand, please feel free to call me out. 🙂

**Comment by menomanabdulla** [comment]
Thank you
