### ISSUE TITLE
Wrong code in javascripting workshop!

### ISSUE THREAD

**Issue by returntruejoy** [nodeschool/dhaka#5]
In the workshop javascripting there is a lesson named "ARRAY FILTERING" and it has these lines of code:
var filtered = pets.filter(function (pet){
    return (pet !== 'elephant');

I have tried to run these lines of code and got the following error:

SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by masnun** [comment]
Close your function declaration.

On Tuesday, March 10, 2015, Sayed Zayeem Abdullah Turjoy <
notifications@github.com> wrote:

> In the workshop javascripting there is a lesson named "ARRAY FILTERING"
> and it has these lines of code:
> var filtered = pets.filter(function (pet){
> return (pet !== 'elephant');
> 
> I have tried to run these lines of code and got the following error:
> 
> SyntaxError: Unexpected token }
> at exports.runInThisContext (vm.js:73:16)
> at Module._compile (module.js:443:25)
> at Object.Module._extensions..js (module.js:478:10)
> at Module.load (module.js:355:32)
> at Function.Module._load (module.js:310:12)
> at Function.Module.runMain (module.js:501:10)
> at startup (node.js:129:16)
> at node.js:814:3
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/dhaka/issues/5.

## 

Abu Ashraf Masnun | +8801711960803 | http://masnun.me

**Comment by az7arul** [comment]
the format is some_array.filter(function (argument) { // statements;});

**Comment by az7arul** [comment]
https://github.com/nodeschool/organizers

**Comment by masnun** [comment]
I will apply tonight. Thanks.

On Tuesday, March 10, 2015, Azharul Islam notifications@github.com wrote:

> https://github.com/nodeschool/organizers
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/dhaka/issues/5#issuecomment-77920154.

## 

Abu Ashraf Masnun | +8801711960803 | http://masnun.me
