### ISSUE TITLE
#3 NodeSchool International Day ( May  23)

### ISSUE THREAD

**Issue by az7arul** [nodeschool/dhaka#7]
@nodeschool/dhaka interested ?

**Comment by az7arul** [comment]
How about this time we try https://github.com/azat-co/expressworks

**Comment by riyadhalnur** [comment]
what venues are we looking at?

the expressworks is good but that shouldn't be the only one. we have people from all levels attending these events. best not to jump straight to expressjs before learning vanilla

**Comment by zhdzmn** [comment]
we can try for the 10th floor of newscred ?

**Comment by az7arul** [comment]
@nodeschool/dhaka we need a venue for 23rd May (sat), 2015

**Comment by az7arul** [comment]
http://www.meetup.com/Dhaka-JS/events/222354776/

**Comment by riyadhalnur** [comment]
We can have NewsCred's 4th floor

**Comment by az7arul** [comment]
@nodeschool/dhaka Since this will be a full day event it would be great if we could get someone to sponsor lunch and snacks

**Comment by riyadhalnur** [comment]
Who do you have in mind? btw I changed the event details. Change the time to the appropriate one

**Comment by ishtiaque23** [comment]
Just talked to the venue provider, we will have it on the 13th floor, please update the meetup event details

**Comment by riyadhalnur** [comment]
on it

**Comment by az7arul** [comment]
Since this will be a day long event how about having a segment where people showcase work they have done using node.js ? 

@nodeschool/dhaka

**Comment by riyadhalnur** [comment]
:+1:

**Comment by atiqueahmedziad** [comment]
:+1:

**Comment by az7arul** [comment]
I propose the following schedule :

10:00 AM - 10.30 AM Introduction / Installation / Intro video recording
10.30 AM - 12.00 AM Learning
12:00 PM - 1:00 PM Lunch Break
1:00 PM - 3:00 PM Learning
3:00 PM - 3:30 PM Coffee Break
3:30 - 5:00 PM Other Activities ( Lightning talks / showcase work / exit video )

**Comment by tauhidul35** [comment]
:+1:

**Comment by returntruejoy** [comment]
[?]

**Comment by hasanmansur** [comment]
Interested but both nodejs & even javascript are new to me.  Can I join?

**Comment by riyadhalnur** [comment]
@hasanmansur yes definitely. nodeschool encourages everyone to join - newbie to advanced :)

**Comment by hasanmansur** [comment]
@riyadhalnur thanks a lot brother. Is there any link in where I should register for this event? Or its just a walkin? Thanks again

**Comment by riyadhalnur** [comment]
@hasanmansur yes, please RSVP to the event here http://www.meetup.com/Dhaka-JS/events/222354776/

**Comment by hasanmansur** [comment]
@riyadhalnur thanks :-)

**Comment by az7arul** [comment]
Anyone interested to showcase / talk about their work with Node.js ?

**Comment by nadimtuhin** [comment]
i can showcase a node gsm modem sms integration app

**Comment by riyadhalnur** [comment]
:+1: @nadimtuhin

**Comment by amuntasim** [comment]
Recently I am developing a reservation portal using sails.js [elasticsearch, mysql, mobile-backend]. 
I can showcase that

**Comment by prappo** [comment]
i am in :)

**Comment by riyadhalnur** [comment]
@amuntasim sounds great :+1:

**Comment by az7arul** [comment]
http://www.meetup.com/Dhaka-JS/messages/boards/thread/48970753/#128074469

**Comment by az7arul** [comment]
@amuntasim @nadimtuhin great, see you guys on 23rd

**Comment by nadimtuhin** [comment]
ok I am preparing

**Comment by amuntasim** [comment]
Should we have any slides or only demo?

**Comment by zhdzmn** [comment]
It is totally upto you guys
however you prefer. The creator of node once had a presentation with just the terminal open :)

**Comment by az7arul** [comment]
@m1sul can you send us your email address ?

**Comment by tanvirraj** [comment]
@az7arul  via here it is  mones0008@gmail.com

**Comment by az7arul** [comment]
Video is here : https://www.youtube.com/watch?v=0YneGGzY0HA

**Comment by tanvirraj** [comment]
:+1:

**Comment by nadimtuhin** [comment]
(y)

On Thu, May 28, 2015 at 11:52 PM, Tanvir Raj notifications@github.com
wrote:

> [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/dhaka/issues/7#issuecomment-106526678.

## 

Regards,
Omar Faruque Tuhin,

Project Manager,
The Software Engineers (TSE),
website: http://tse.com.bd,
email: info@tse.com.bd

**Comment by raihantaher** [comment]
Nice video.

**Comment by jeebon** [comment]
So nice....
