### ISSUE TITLE
Next university IUB

### ISSUE THREAD

**Issue by zhdzmn** [nodeschool/dhaka#8]
Guys just talked to Ashraful Amin sir, he is very eager for us to be in their premise and do a nodeschool session. I will update the timing here. stay tuned.

Interested mentors ?

**Comment by az7arul** [comment]
+1

**Comment by ishtiaque23** [comment]
count me in.

**Comment by prappo** [comment]
is it only for IUB students ?

**Comment by zhdzmn** [comment]
yes

**Comment by prappo** [comment]
I want to arrange it in my university , => UITS

**Comment by zhdzmn** [comment]
Sure why not

**Comment by az7arul** [comment]
update ?

**Comment by zhdzmn** [comment]
Only one it will happen after 12 th

**Comment by zhdzmn** [comment]
Ok got the final dates. It is in 28 th may. Thursday. Who are interested to be the mentors? Remember this is a private event for iub only

**Comment by zhdzmn** [comment]
Time is after lunch probably from 3 pm

**Comment by az7arul** [comment]
interested

**Comment by prappo** [comment]
interested as volunteer not mentor

**Comment by zhdzmn** [comment]
@az7arul care to setup a meetup for this ?

**Comment by amuntasim** [comment]
I'm interested

**Comment by az7arul** [comment]
@amuntasim the date moved to saturday ( 30 ) from thursday (28)

**Comment by amuntasim** [comment]
No problem, Saturday same time?

**Comment by zhdzmn** [comment]
the thursday was a problem for them. so they moved it to saturday 10 AM - 1 PM

**Comment by zhdzmn** [comment]
is everyone ok with that

**Comment by amuntasim** [comment]
InshaAllah

**Comment by prappo** [comment]
ok

**Comment by atiqueahmedziad** [comment]
Any meetup link or reg. Link?  need to update the next event info. in the site :)

**Comment by az7arul** [comment]
@atiqueahmedziad http://www.meetup.com/Dhaka-JS/events/222751001/

**Comment by zhdzmn** [comment]
thanks for coming @prappo @amuntasim @ishtiaque23 @az7arul
