### ISSUE TITLE
Node Js c++ code base

### ISSUE THREAD

**Issue by Shafiul-Hasan-tareq** [nodeschool/dhaka#9]
Hi Guys,

I was just wondering if anybody of us ever explored node/iojs 's c++ code base? I think, we should explore the codebase and send some pull request to the main repo. I am little bit weak in c++, so if anybody already have explored the codebase and wants to help me then it will be great. 

Thanks,
Tareq.

**Comment by max-mapper** [comment]
also check out the 'going-native' workshop on http://nodeschool.io/

**Comment by riyadhalnur** [comment]
At the moment, I think `io.js` would be better to send PRs to. Their development cycle is faster. Let me know if you find anything. I'll look into their issues list.
